version: '3'
volumes:
  postgres_data:
  public_data:
  tmp_data:
  log_data:
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
    - .:/myapp
    - public_data:/myapp/public
    - tmp_data:/myapp/tmp
    - log_data:/myapp/log
    ports:
      - 3000:3000
    depends_on:
    - db
  nginx:
    build: .
    volumes:
      - public_data:/myapp/public
      - tmp_data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - web
  
  # pgadmin4:
  #   image: dpage/pgadmin4:4.2
  #   container_name: pgadmin4
  #   ports:
  #       - 8000:8000
  #   volumes:
  #       - ./docker/pgadmin4:/var/lib/pgadmin
  #   environment:
  #       PGADMIN_DEFAULT_EMAIL: root
  #       PGADMIN_DEFAULT_PASSWORD: root
  #   hostname: pgadmin4
  #   depends_on:
  #     - postgres
  #   restart: always