version: '3'
volumes:
  postgres_data:
  public_data:
  tmp_data:
  log_data:
  pgadmin4-data:
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
    - .:/myapp
    - public_data:/myapp/public
    - tmp_data:/myapp/tmp
    - log_data:/myapp/log
    ports:
      - 3000:3000
    depends_on:
    - db
    environment:
      DATABASE_HOST: db
  nginx:
    build: .
    volumes:
      - public_data:/myapp/public
      - tmp_data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - web
  pgadmin4:
    image: dpage/pgadmin4:4.2
    restart: always
    container_name: pgadmin4
    ports:
      - 8000:80
    volumes:
      - pgadmin4-data:/var/lib/pgadmin
    environment:
      TZ: Asia/Tokyo
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - db